DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS plants CASCADE;
DROP TABLE IF EXISTS greenhouse CASCADE;
DROP TABLE IF EXISTS categories CASCADE;

CREATE TABLE users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(256) NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL
);

CREATE TABLE plants (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name  VARCHAR(256) NOT NULL,
    description TEXT NOT NULL,
    scientific_name VARCHAR(256),
    image TEXT NOT NULL
);

CREATE TABLE greenhouse (
    user_plant_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    users_id BIGINT REFERENCES users(id),
    plant_id BIGINT REFERENCES plants(plant_id),
    on_market BOOLEAN NOT NULL
);

CREATE TABLE categories (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);


